# ffprobe -v quiet -print_format json -show_format -show_streams -show_error https://shoutcast.mbari.org/pacific-soundscape
STREAM_SAMPLE_RATE: 48000
STREAM_CHANNELS: 2
BIT_DEPTH: 16
BIT_RATE: 128000
CHANNEL_LAYOUT: stereo
CODEC_NAME: mp3
SAMPLE_FMT: fltp

STREAM_URL: https://shoutcast.mbari.org/pacific-soundscape

output_file: "/data/output.mp3"
duration: 30.0
chunk_size: 1024
sample_rate: 16000 # for microphone or other recording
display_len: 128

#### LOG LEVELS ####
# NOTSET: 0
# DEBUG: 10
# INFO: 20
# WARN: 30
# ERROR: 40
# CRITICAL: 50
####################
log_level: 20
log_file: "/dev/stdout"
