PROJECT_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/'
INPUT_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/MARS-detector/'
OUTPUT_ROOT: /workspaces/mbari-hydrophone-stream-monitor/MARS-detector/'

DATA_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/MARS-data-tagger/assets/data/'
DATASET_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/MARS-data-tagger/'

MODEL_NAME: 'tbd'

N_EPOCHS: 4
N_BATCH: 32
RANDOM_STATE: 256
SAMPLE_SIZE: 1.0
TEST_SIZE: 0.2
CONFIDENCE: 0.15

spectrogram_params:
    fs: 48000
    nfft: 512
    nperseg: 512
    noverlap: 128
    window: 'hann'