DATA_ROOT: '/data/'
MODEL_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/MARS-detector/models/'

MODEL_NAME: 'net'

melspec_params:
    n_mels: 180
    n_fft: 512
    power: 2
    win_length: 512
    hop_length: 384
    