DATA_ROOT: '/data/'
MODEL_ROOT: '/workspaces/mbari-hydrophone-stream-monitor/MARS-detector/models/'

MODEL_NAME: 'net'

TRAIN: False
SAVE: False


N_EPOCHS: 20
N_BATCH: 32
RANDOM_STATE: 256
SAMPLE_SIZE: 1.0
TEST_SIZE: 0.2
LEARNING_RATE: 0.001
MOMENTUM: 0.9

torch_spectrogram_params:
    n_fft: 512
    power: 2
    win_length: 512
    hop_length: 384

torch_melspec_params:
    n_mels: 180
    n_fft: 512
    power: 2
    win_length: 512
    hop_length: 384